'use strict';
/* Angles 8–14.
   NOTE on two angles:
   - SOCIAL_PROOF uses {{RATING}} / {{COUNT}} / {{QUOTE}} / {{NAME}} placeholders and is
     `requiresRealData:true`. It is EXCLUDED from the build unless real review data is
     supplied. Inventing ratings or testimonials would be fabricating records.
   - PRACTITIONER never asserts an endorsement. It frames clinician conversation only. */

module.exports = [

{ code:'RITUAL', name:'Daily ritual', desire:'Support the GLP-1 journey',
  eyebrows:['Two capsules daily','60 capsules · one month','Morning routine','The daily step'],
  headlines:[
    'Two capsules. Every morning. That’s it.',
    'The simplest part of your routine.',
    'Two capsules, 6–8 oz of water, done.',
    'A ten-second habit.',
    'One bottle. One month. One habit.',
    'Morning, water, two capsules.',
    'The easiest thing you’ll do today.',
    'No powder. No shaker. No fuss.',
    '60 capsules. 30 mornings.',
    'Add one step. Keep everything else.',
    'A routine you’ll actually keep.',
    'Small habit. Long journey.',
    'Take it with your morning water.',
    'The low-effort half of your protocol.',
    'Simple enough to do on the bad days.',
    'Two capsules is the whole instruction.',
    'Designed to be easy to keep up.',
    'One month per bottle. No guessing.',
    'The habit that doesn’t need willpower.',
    'Ten seconds a morning.',
    'Capsules, not powders.',
    'It fits in the routine you already have.',
    'The daily step that asks nothing of you.',
    'Simplicity is the feature.',
    'A habit small enough to survive a bad week.',
    'No mixing. No measuring. No excuses.',
    'Two a day. Every day. That’s the protocol.',
    'The boring habit that adds up.',
    'Easy to start. Easier to keep.',
    'Your morning, plus ten seconds.',
  ],
  subheads:[
    'As a dietary supplement, take two capsules daily with 6–8 oz of water.',
    '60 capsules per bottle — a full month of mornings.',
    'Capsule format. No powder, no shaker, no flavour to tolerate.',
    'Built to be kept, not just bought.',
  ]},

{ code:'CLEAN_LABEL', name:'Clean label', desire:'Support the GLP-1 journey',
  eyebrows:['Eight things it isn’t','Read the label','Plainly labelled','Non-GMO · Vegetarian'],
  headlines:[
    'Eight things LF-1 isn’t.',
    'Read the label. That’s the pitch.',
    'Non-GMO. Vegetarian. Allergen-free.',
    'Nothing you have to look up.',
    'A label you can read in one breath.',
    'No hormones. No antibiotics. No alcohol.',
    'Vegetarian capsules, plainly labelled.',
    'Gluten-free. Lactose-free. Allergen-free.',
    'The short ingredient list is the point.',
    'Clean label isn’t a claim. It’s a list.',
    'What’s not in it matters too.',
    'Eight certifications. One capsule.',
    'Transparent by default.',
    'If you read labels, read this one.',
    'No mystery blends in the marketing.',
    'Plain label. Plain language.',
    'Made without the usual suspects.',
    'Certified eight ways.',
    'Honest labelling, European standards.',
    'For people who turn the bottle around.',
    'Vegetarian. Non-GMO. Nothing hidden.',
    'The bottle says what it is.',
    'Nothing to squint at.',
    'Clean enough to explain in a sentence.',
    'Free from eight things you’d rather avoid.',
    'A supplement that survives a label check.',
    'Made in the USA. Labelled for the EU.',
    'No hormones, no antibiotics, no shortcuts.',
    'Simple label. Specific purpose.',
    'Turn the bottle around. We’ll wait.',
  ],
  subheads:[
    'Non-GMO, gluten-free, lactose-free, allergen-free, antibiotic-free, hormone-free, alcohol-free, vegetarian.',
    'Manufactured in the USA. Sold under EU labelling standards.',
    '60 vegetarian capsules. Two daily.',
    'Everything on the label, nothing behind it.',
  ]},

{ code:'PRACTITIONER', name:'Clinician conversation', desire:'Support the GLP-1 journey',
  eyebrows:['Worth asking about','Bring it to your next appointment','A question for your clinician'],
  headlines:[
    'The question worth asking at your next appointment.',
    'Bring this up with your clinician.',
    'Ask about digestive support. Specifically.',
    'A question most people don’t think to ask.',
    'Worth raising at the three-month check-in.',
    'The thing to ask before you consider stopping.',
    'Add it to your list of questions.',
    'Most appointments cover the dose. Ask about the rest.',
    'One question changes the conversation.',
    'What to ask when the appointment is short.',
    'Ten minutes with your clinician. Spend one on this.',
    'The follow-up question that matters.',
    'Ask about the gut half of the plan.',
    'Your next appointment, better prepared.',
    'A better question than "is this normal?"',
    'Take the question with you.',
    'Worth a conversation, not a guess.',
    'Talk to someone before you change anything.',
    'The part of the plan worth discussing.',
    'Bring the bottle. Ask the question.',
    'Ask, don’t assume.',
    'A five-second question with a long answer.',
    'Put digestive support on the agenda.',
    'Prepared patients get better appointments.',
    'What would you ask if you had more time?',
    'Discuss it properly.',
    'One line for your notes app before the appointment.',
    'The conversation worth having.',
    'Ask your clinician about daily digestive support.',
    'Before you change the dose, ask about this.',
  ],
  subheads:[
    'LF-1 is a food supplement, not medical advice. Talk to your healthcare professional.',
    'Consult a physician if pregnant, nursing, under 18, or managing a medical condition.',
    'Always discuss changes to your GLP-1 routine with the clinician who prescribed it.',
    'A daily digestive companion — bring it up at your next appointment.',
  ]},

{ code:'NUTRIENT_GAP', name:'The nutrient gap', desire:'Specific GLP-1 problems',
  eyebrows:['Eating less, absorbing less','The intake question','Smaller plates, same needs'],
  headlines:[
    'Eating less doesn’t mean needing less.',
    'Smaller plates. Same requirements.',
    'Your appetite dropped. Your needs didn’t.',
    'Less food in. Same body to run.',
    'When portions shrink, intake shrinks with them.',
    'Half the plate. All the same requirements.',
    'The maths nobody does on a GLP-1.',
    'Appetite is down. Nutrition still counts.',
    'Fewer meals, same daily needs.',
    'What happens when you simply eat less.',
    'Your body didn’t lower its requirements.',
    'Eating like a bird. Still built like a person.',
    'The gap between eating less and needing less.',
    'Smaller portions, unchanged nutrition targets.',
    'A GLP-1 changes intake. Plan for it.',
    'Reduced appetite is the point. Reduced intake is the side effect.',
    'You’re eating less. That’s working. Now cover the gap.',
    'The quiet arithmetic of a smaller appetite.',
    'Less on the plate. More reason to supplement.',
    'When you eat half as much, what comes with it?',
    'Appetite suppression works. Nutrition still matters.',
    'The intake question nobody asks.',
    'Smaller meals, same daily maths.',
    'Mind the gap between appetite and requirement.',
    'Your plate got smaller. Your needs stayed put.',
    'Fewer calories in means fewer of everything in.',
    'The trade-off worth planning for.',
    'Eat less. Cover the difference.',
    'What a shrinking appetite quietly takes with it.',
    'The gap is real. Close it daily.',
  ],
  subheads:[
    'A GLP-1 reduces appetite — and everything that comes in with food.',
    'LF-1 is a daily supplement taken alongside your routine.',
    'Two capsules daily. Contains iron.',
    'Formulated for people eating substantially less than before.',
  ],
  /* EFSA-authorised wordings. Gated: usable only if LF-1 delivers >=15% NRV iron
     per serving. Confirm against the Supplement Facts panel before enabling. */
  gatedClaims:[
    { text:'Iron contributes to the reduction of tiredness and fatigue.', basis:'EFSA authorised', needsVerify:true },
    { text:'Iron contributes to normal energy-yielding metabolism.', basis:'EFSA authorised', needsVerify:true },
    { text:'Iron contributes to normal oxygen transport in the body.', basis:'EFSA authorised', needsVerify:true },
    { text:'Iron contributes to normal formation of red blood cells and haemoglobin.', basis:'EFSA authorised', needsVerify:true },
    { text:'Iron contributes to normal cognitive function.', basis:'EFSA authorised', needsVerify:true },
    { text:'Iron contributes to the normal function of the immune system.', basis:'EFSA authorised', needsVerify:true },
  ]},

{ code:'CONFIDENCE', name:'Back to life', desire:'Support the GLP-1 journey',
  eyebrows:['Say yes again','Back to plans','For the calendar, not the scale'],
  headlines:[
    'Say yes to the dinner again.',
    'Back to making plans.',
    'Let your calendar catch up.',
    'For the mornings you have somewhere to be.',
    'Plans you don’t have to think twice about.',
    'Stop planning your day around your gut.',
    'The restaurant. The flight. The long meeting.',
    'Be somewhere without a contingency plan.',
    'Comfortable enough to forget about it.',
    'Freedom is not thinking about it.',
    'Your day, uninterrupted.',
    'Make the plans. Keep the plans.',
    'For people with somewhere to be.',
    'Get your mornings back on the calendar.',
    'Leave the house without a strategy.',
    'The goal isn’t just progress. It’s living.',
    'Back to normal-sized worries.',
    'A day that doesn’t revolve around timing.',
    'Say yes without doing the maths first.',
    'Plans, not contingencies.',
    'For the parts of life that don’t wait.',
    'Show up. Stay comfortable.',
    'Get on with your day.',
    'The point was always to live more.',
    'Book the table.',
    'Stop negotiating with your morning.',
    'Be present, not preoccupied.',
    'Your life, back on schedule.',
    'Forget about it by 9am.',
    'Progress you don’t have to plan around.',
  ],
  subheads:[
    'LF-1 is daily digestive support for people on a GLP-1.',
    'Two capsules each morning, so the rest of the day is yours.',
    'Made for the routine, so you can get on with everything else.',
    'The daily step that makes the other steps easier.',
  ]},

{ code:'OFFER', name:'Offer & risk reversal', desire:'Conversion',
  eyebrows:['€49 · 60 capsules','One month supply','Direct from LEAF','Free US shipping'],
  headlines:[
    '€49. One month. Sixty capsules.',
    'A month of support for €49.',
    'Sixty capsules. One simple price.',
    'Less than €1.65 a morning.',
    'One bottle. One month. €49.',
    'Start with one month.',
    'No subscription required to try it.',
    '€49 direct from LEAF.',
    'The whole month, one price.',
    'Try one bottle before anything else.',
    'Thirty mornings, sixty capsules, €49.',
    'Straightforward price. Straightforward product.',
    'What a month of support costs.',
    'One month at a time.',
    'Priced like a supplement, not a programme.',
    'No bundles to decode.',
    'Simple pricing for a simple habit.',
    'Begin with a single bottle.',
    'One month. Then decide.',
    '€49 for the companion half of your routine.',
    'Sixty capsules, shipped free to the US.',
    'One price. No tiers.',
    'Start here: one bottle, €49.',
    'A month’s supply, plainly priced.',
    'Order one. See how the month goes.',
    'Try a month.',
    'The price is on the page. No funnel.',
    'One bottle is enough to start.',
    'A month of mornings for €49.',
    'Take one month at a time.',
  ],
  subheads:[
    'LF-1 — 60 capsules, €49. Two capsules daily. Available at leaf-pure.com.',
    'One bottle is one month. Start there.',
    'Sold by LEAF, a Netherlands-based brand.',
    'Ships from the USA. Priced in euro.',
  ]},

{ code:'SOCIAL_PROOF', name:'Social proof', desire:'Conversion',
  requiresRealData:true,
  eyebrows:['{{COUNT}}+ on a GLP-1','Rated {{RATING}}/5','From the reviews'],
  headlines:[
    'Rated {{RATING}}/5 by {{COUNT}}+ people on a GLP-1.',
    '{{COUNT}}+ people took it this morning.',
    '"{{QUOTE}}" — {{NAME}}',
    'What {{COUNT}}+ customers said.',
    '{{RATING}}/5 ★★★★★',
    'Join {{COUNT}}+ people on the same routine.',
    'The reviews say it better than we can.',
    '{{COUNT}}+ mornings and counting.',
  ],
  subheads:[
    'Review data must be supplied from the LEAF store before these render.',
    'Verified customer reviews, leaf-pure.com.',
  ]},

];
