'use strict';
/* Angles 1–7. Every headline hand-written against the Ad Library corpus.
   Rules enforced: no drug brand names; no treat/cure/prevent/fix/eliminate;
   no second-person health-status assertions; no weight or outcome promises. */

module.exports = [

{ code:'FINALLY_NORMAL', name:'Finally normal', desire:'Support the GLP-1 journey',
  eyebrows:['Daily GLP-1 companion','For life on a GLP-1','LEAF · LF-1','Made for GLP-1 routines','The companion capsule'],
  headlines:[
    'Finally, a GLP-1 morning that feels normal.',
    'We take care of your GLP-1 sides.',
    'The sides nobody warns you about.',
    'Your GLP-1, minus the sides.',
    'Finally. Mornings that feel like yours.',
    'Feel normal. Stay the course.',
    'Your GLP-1 is doing its job. LF-1 handles the rest.',
    'Built for the part nobody warned you about.',
    'Normal is underrated. Get it back.',
    'The companion your GLP-1 came without.',
    'Finally — made for a GLP-1 routine.',
    'Same goals. Better mornings.',
    'For the days your GLP-1 doesn’t cover.',
    'Steady mornings start here.',
    'Because "on track" should feel like it.',
    'The missing half of your GLP-1 routine.',
    'Two capsules. Normal mornings.',
    'On your GLP-1. Finally comfortable.',
    'The quiet part of the journey, handled.',
    'Not a shortcut. A steadier ride.',
    'The GLP-1 support that should have come in the box.',
    'Finally, a routine that keeps up with you.',
    'Comfort, without changing course.',
    'Where your GLP-1 stops, LF-1 starts.',
    'Progress you can actually live with.',
    'Designed for GLP-1 mornings.',
    'Stay on plan. Feel better doing it.',
    'For everything the prescription didn’t mention.',
    'Your journey. Properly supported.',
    'Feel like yourself again.',
    'The other half of the protocol.',
    'Finally, support built for this exact moment.',
    'Less guesswork. Steadier days.',
  ],
  subheads:[
    'LF-1 is a daily digestive companion made for people on a GLP-1.',
    'Two capsules each morning. 60 per bottle.',
    'A companion to your GLP-1 — never a replacement for it.',
    'Built around the routine, not around the scale.',
    'Digestive support, formulated for GLP-1 routines.',
    'For the mornings your plan depends on.',
    'One simple daily step alongside your GLP-1.',
    'Made for the long stretch, not the first week.',
  ]},

{ code:'GI_SPECIFIC', name:'Digestive specificity', desire:'GLP-1 side effects',
  eyebrows:['Digestive support','Daily regularity support','GI comfort, daily','Gut-first formulation','Digestive Support · LF-1'],
  headlines:[
    'Built for a GLP-1 gut.',
    'No laxatives in the formula.',
    'Built for injections and oral GLP-1s alike.',
    'Whole ingredients. Zero compromise.',
    'Digestive comfort, on a GLP-1 schedule.',
    'Slower digestion deserves smarter support.',
    'GLP-1 mornings, made easier.',
    'Regularity support, built for this routine.',
    'For the part of the journey nobody posts about.',
    'A GLP-1 slows things down. LF-1 supports the rest.',
    'Daily digestive support. Nothing dramatic.',
    'Gut support that understands the assignment.',
    'Made for how a GLP-1 actually works.',
    'Comfort is part of progress.',
    'The unglamorous half of the journey.',
    'Digestive support that fits the protocol.',
    'When appetite drops, digestion changes. Support it.',
    'For GLP-1 routines that need a steadier gut.',
    'Formulated for slower digestion.',
    'Support the system your GLP-1 slows down.',
    'Everyday digestive support. Every single morning.',
    'The gut half of GLP-1 support.',
    'Because comfort shouldn’t be the trade-off.',
    'Daily support for GLP-1 digestion.',
    'Gentle, daily, and built for this.',
    'Slower gut. Steadier support.',
    'Digestive support, minus the drama.',
    'Made for the mornings in between.',
    'Your gut is on this journey too.',
    'Support that starts where the appetite stops.',
    'Digestion changes on a GLP-1. Plan for it.',
    'Built for GLP-1 digestion, not general wellness.',
    'The daily step your gut was missing.',
  ],
  subheads:[
    'LF-1 is formulated as daily digestive support for people on a GLP-1.',
    'Category: Digestive Support. Dose: two capsules daily.',
    'Appetite falls on a GLP-1 — digestion changes with it.',
    'Designed around slower gastric emptying, not general gut health.',
    'A daily capsule made for GLP-1 digestion.',
    'Support the gut through the whole course.',
    'Two capsules with 6–8 oz of water, every morning.',
    'Made for the routine you’re already keeping.',
  ]},

{ code:'STAY_COURSE', name:'Stay the course', desire:'Support the GLP-1 journey',
  eyebrows:['Stay on track','Built for the long stretch','Month three and beyond','For the full course'],
  headlines:[
    'Don’t quit the plan. Support it.',
    'The goal is to stay on it.',
    'Month one is easy. LF-1 is for month four.',
    'Built for the long stretch.',
    'Most people stop for reasons nobody talks about.',
    'Staying on track is the whole game.',
    'Support the course you already committed to.',
    'The plan works if you can stay on it.',
    'Made for people who intend to finish.',
    'Consistency needs support too.',
    'Week 1 motivation. Month 6 support.',
    'For everyone still going.',
    'The long game needs a daily habit.',
    'Keep going. Comfortably.',
    'Your plan deserves a support plan.',
    'Stay the course, feel the difference.',
    'Built for the months, not the moment.',
    'The reason people stop isn’t motivation.',
    'Finish what you started.',
    'Designed for the people still on it.',
    'Support now, so you don’t stop later.',
    'Make month six as easy as month one.',
    'A daily habit for a long commitment.',
    'The journey is longer than the hype.',
    'Consistency, supported daily.',
    'Still on your GLP-1? This is for you.',
    'Keep the routine. Add the support.',
    'For the long, unglamorous middle.',
    'Built for people who don’t quit.',
    'Stay on. Feel steadier.',
  ],
  subheads:[
    'LF-1 is daily digestive support designed for people staying on a GLP-1.',
    'A companion for the whole course — not a replacement for it.',
    'Two capsules daily. 60 per bottle. One month at a time.',
    'Built for month four, not just week one.',
    'Support the routine you already committed to.',
    'Made for the long middle of the journey.',
  ]},

{ code:'FIBER_FAILS', name:'Mechanism reframe', desire:'Specific GLP-1 problems',
  eyebrows:['Think beyond fiber','A different approach','Not another fiber scoop','Mechanism matters'],
  headlines:[
    'GLP-1? Think beyond fiber.',
    'Why a generic fiber scoop isn’t built for this.',
    'A GLP-1 gut isn’t a normal gut.',
    'Fiber alone wasn’t designed for this routine.',
    'Same problem. Different mechanism.',
    'Your usual fix wasn’t built for a GLP-1.',
    'Not a fiber scoop. A formulation.',
    'General gut products solve a general problem.',
    'Built for the mechanism, not the symptom.',
    'A GLP-1 changes the timing. Support should match.',
    'Most gut supplements ignore the GLP-1 variable.',
    'Don\u2019t support a GLP-1 gut like an average one.',
    'The routine changed. The support should too.',
    'Fiber is a tool. Not the whole toolbox.',
    'Different cause. Different support.',
    'Why "more fiber" is incomplete advice.',
    'Designed for slower gastric emptying.',
    'Built around how a GLP-1 actually behaves.',
    'Generic gut support, meet a specific routine.',
    'Your gut changed. Your support didn’t.',
    'The mechanism is the message.',
    'Precision beats more scoops.',
    'Made for this routine specifically.',
    'A specific routine deserves specific support.',
    'Not more. Different.',
    'The fix isn’t volume. It’s fit.',
    'Built for GLP-1 physiology.',
    'One-size-fits-all stops fitting on a GLP-1.',
    'Rethink the gut half of your protocol.',
    'Beyond fiber. Built for this.',
  ],
  subheads:[
    'LF-1 is formulated specifically as digestive support for GLP-1 routines.',
    'A GLP-1 slows gastric emptying — support should account for that.',
    'Digestive Support, purpose-built rather than general-purpose.',
    'Two capsules daily, designed around the routine you’re on.',
    'Not a scoop. Not a powder. A daily capsule.',
  ]},

{ code:'COMPANION', name:'The companion', desire:'Support the GLP-1 journey',
  eyebrows:['Your GLP-1 companion','The other half','Companion capsule','Built to sit alongside'],
  headlines:[
    'Your GLP-1 companion.',
    'The all-in-one built for your GLP-1 journey.',
    'One prescription. One companion.',
    'Made to sit beside your GLP-1.',
    'A companion, never a replacement.',
    'The second half of the protocol.',
    'Your GLP-1 handles appetite. LF-1 handles the rest.',
    'Two things in your routine. One works on the gut.',
    'Built to work alongside, not instead.',
    'The daily companion to a weekly routine.',
    'Everything the prescription didn’t include.',
    'One capsule format. One clear job.',
    'Support that knows its role.',
    'Alongside your GLP-1, every morning.',
    'The companion piece.',
    'Your routine has a gap. This fills it.',
    'Purpose-built to complement, not compete.',
    'Pair it with the plan you’re already on.',
    'A daily companion for a long journey.',
    'It doesn’t replace anything. It supports everything.',
    'The part of the routine you choose.',
    'Designed to be the other half.',
    'Complete the protocol.',
    'Prescription plus companion.',
    'Built for what comes with it.',
    'One job, done daily.',
    'The companion capsule for GLP-1 routines.',
    'Your plan, properly paired.',
    'Made to be the second thing you take.',
    'Beside your GLP-1, not instead of it.',
  ],
  subheads:[
    'LF-1 is a daily digestive companion — it does not replace your GLP-1.',
    'Take two capsules daily alongside your existing routine.',
    'Designed to complement a prescribed GLP-1, never to substitute for one.',
    '60 capsules. One month. One simple job.',
    'The companion half of a two-part routine.',
  ]},

{ code:'NO_MANUAL', name:'No manual', desire:'Support the GLP-1 journey',
  eyebrows:['Nobody handed you a manual','The missing instructions','What nobody mentioned'],
  headlines:[
    'Because a GLP-1 doesn’t come with a manual.',
    'Nobody hands you the instructions.',
    'The part of the appointment that got skipped.',
    'You got the prescription. Not the playbook.',
    'What the leaflet left out.',
    'Everybody covers week one. Nobody covers week nine.',
    'The conversation nobody had with you.',
    'No manual. No warning. Just figure it out.',
    'The missing page of the instructions.',
    'What they don’t tell you at the pharmacy.',
    'Prescribed in ten minutes. Lived for months.',
    'The brief nobody gave you.',
    'Here’s the part they left out.',
    'You were told what it does. Not what to expect.',
    'The follow-up appointment you never got.',
    'Consider this the missing instructions.',
    'Nobody prepares you for the middle part.',
    'A prescription isn’t a plan.',
    'The gap between prescribed and supported.',
    'You figured out the shot. Now the rest.',
    'What the pamphlet skipped.',
    'The support nobody scheduled for you.',
    'Written for the part you’re living now.',
    'Ten minutes of guidance. Months of reality.',
    'The instructions you deserved.',
    'Nobody mentioned this bit.',
    'Filling in what the leaflet didn’t.',
    'The missing chapter.',
    'You weren’t told. Now you are.',
    'Between the prescription and real life.',
  ],
  subheads:[
    'LF-1 is daily digestive support for the part of the journey nobody briefs you on.',
    'Made for people already on a GLP-1 and figuring out the rest.',
    'Two capsules daily. A simple answer to an unasked question.',
    'Support for the months after the first appointment.',
    'Not medical advice — a daily companion. Talk to your clinician.',
  ]},

{ code:'EURO_STANDARD', name:'European standard', desire:'Support the GLP-1 journey',
  eyebrows:['From the Netherlands','European labelling standards','Made to EU standards','Amsterdam · LEAF'],
  headlines:[
    'Sold under European labelling standards.',
    'A Dutch approach to GLP-1 support.',
    'European standards. Daily routine.',
    'Made by a European brand, for European routines.',
    'From Amsterdam, for your GLP-1 journey.',
    'Held to EU labelling standards.',
    'European rigour, daily format.',
    'Built where the rules are strict.',
    'EU standards aren’t a marketing line. They’re the law.',
    'A European take on daily GLP-1 support.',
    'Claims held to European regulation.',
    'The Dutch don’t do exaggerated claims.',
    'Made to the standards we’re held to.',
    'Regulated market. Honest label.',
    'European brand. Transparent formulation.',
    'Where claims have to be proven.',
    'LEAF is a Netherlands company.',
    'European compliance, by default.',
    'Built for a market that checks.',
    'Strict standards, simple capsule.',
    'The EU version of GLP-1 support.',
    'No hype. European labelling rules.',
    'Amsterdam-based. Plainly labelled.',
    'A European standard for daily support.',
    'Made under rules that don’t allow shortcuts.',
    'Honest by regulation.',
    'European brand, global routine.',
    'Standards first. Claims second.',
    'From a market that audits its labels.',
    'Dutch brand. Direct language.',
  ],
  subheads:[
    'LEAF is a Netherlands-based brand. LF-1 is manufactured in the USA.',
    'Sold across the EU under European food-supplement labelling rules.',
    'European standards mean claims have to be substantiated.',
    'Non-GMO, vegetarian, allergen-free. Plainly labelled.',
    'A European company, a plainly described product.',
  ]},

];
